/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toscana.view.sale;

import com.toscana.controller.payment.ProductSaleViewController;
import com.toscana.model.products.ProductsNames;

/**
 *
 * @author Arandi
 */
//Cambiar el nombre por UIProductsSale
//Especifica que no es la venta de un solo producto
public class UIProductsSale extends javax.swing.JFrame {

    /**
     * Creates new form UIProductSale
     */
    public UIProductsSale() {
        initComponents();
        productSaleViewController = new ProductSaleViewController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saleProductsTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        createNewSaleBtn = new javax.swing.JButton();
        cashSaleBtn = new javax.swing.JButton();
        totalCashToPayField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonCoca600 = new javax.swing.JButton();
        buttonCoca1L = new javax.swing.JButton();
        buttonCocaLight = new javax.swing.JButton();
        buttonNestea = new javax.swing.JButton();
        buttonAguaNatural = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonManjar = new javax.swing.JButton();
        buttonSupAtun = new javax.swing.JButton();
        buttonDeseo = new javax.swing.JButton();
        buttonExquisita = new javax.swing.JButton();
        buttonIrresistible = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonMarcoPolo = new javax.swing.JButton();
        buttonDeliciosa = new javax.swing.JButton();
        buttonMixta = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        buttonToscana = new javax.swing.JButton();
        buttonVegetariana = new javax.swing.JButton();
        buttonSupSalmon = new javax.swing.JButton();
        buttonDelicatessen = new javax.swing.JButton();
        buttonVenecia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toscana - POS");
        setName("UISales"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        saleProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        saleProductsTable.setEnabled(false);
        jScrollPane2.setViewportView(saleProductsTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles de venta"));

        createNewSaleBtn.setText("Nueva Venta");
        createNewSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewSaleBtnActionPerformed(evt);
            }
        });

        cashSaleBtn.setText("Cobrar");
        cashSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashSaleBtnActionPerformed(evt);
            }
        });

        totalCashToPayField.setEnabled(false);
        totalCashToPayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCashToPayFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Total:");

        jButton1.setText("Corte de Caja");

        jButton2.setText("Retiro de Efectivo");

        jButton3.setText("Arqueo");

        jButton4.setText("Cierre de Sesión");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewSaleBtn)
                .addGap(18, 18, 18)
                .addComponent(cashSaleBtn)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalCashToPayField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cashSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createNewSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(totalCashToPayField)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));

        buttonCoca600.setText("Coca-Cola 600");
        buttonCoca600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCoca600ActionPerformed(evt);
            }
        });

        buttonCoca1L.setText("Coca-Cola 1L");
        buttonCoca1L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCoca1LActionPerformed(evt);
            }
        });

        buttonCocaLight.setText("Coca-Cola light");
        buttonCocaLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCocaLightActionPerformed(evt);
            }
        });

        buttonNestea.setText("NestTea 600");
        buttonNestea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNesteaActionPerformed(evt);
            }
        });

        buttonAguaNatural.setText("Agua Natural 500");
        buttonAguaNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAguaNaturalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAguaNatural, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCoca600, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonCoca1L)
                .addGap(18, 18, 18)
                .addComponent(buttonCocaLight)
                .addGap(18, 18, 18)
                .addComponent(buttonNestea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCoca600, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(buttonCoca1L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCocaLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNestea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(buttonAguaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Baguettes"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Las más pedidas"));

        buttonManjar.setText("Manjar");
        buttonManjar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManjarActionPerformed(evt);
            }
        });

        buttonSupAtun.setText("Sup Atún");
        buttonSupAtun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupAtunActionPerformed(evt);
            }
        });

        buttonDeseo.setText("Deseo");
        buttonDeseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeseoActionPerformed(evt);
            }
        });

        buttonExquisita.setText("Exquisita");
        buttonExquisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExquisitaActionPerformed(evt);
            }
        });

        buttonIrresistible.setText("Irresistible");
        buttonIrresistible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIrresistibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonManjar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExquisita, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(buttonIrresistible))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(buttonSupAtun)
                        .addGap(32, 32, 32)
                        .addComponent(buttonDeseo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonManjar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExquisita, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIrresistible, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSupAtun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeseo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Las económicas"));

        buttonMarcoPolo.setText("Marco Polo");
        buttonMarcoPolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMarcoPoloActionPerformed(evt);
            }
        });

        buttonDeliciosa.setText("Deliciosa");
        buttonDeliciosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeliciosaActionPerformed(evt);
            }
        });

        buttonMixta.setText("Mixta");
        buttonMixta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMixtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDeliciosa)
                .addGap(18, 18, 18)
                .addComponent(buttonMarcoPolo)
                .addGap(18, 18, 18)
                .addComponent(buttonMixta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeliciosa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMarcoPolo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMixta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Las Especiales"));

        buttonToscana.setText("Toscana");
        buttonToscana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToscanaActionPerformed(evt);
            }
        });

        buttonVegetariana.setText("Vegetariana");
        buttonVegetariana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVegetarianaActionPerformed(evt);
            }
        });

        buttonSupSalmon.setText("Sup. Salmón");
        buttonSupSalmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupSalmonActionPerformed(evt);
            }
        });

        buttonDelicatessen.setText("Delicatessen");
        buttonDelicatessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelicatessenActionPerformed(evt);
            }
        });

        buttonVenecia.setText("Venecia");
        buttonVenecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVeneciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonToscana, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVegetariana)
                .addGap(18, 18, 18)
                .addComponent(buttonVenecia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSupSalmon)
                .addGap(27, 27, 27)
                .addComponent(buttonDelicatessen)
                .addGap(60, 60, 60))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVegetariana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVenecia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonToscana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelicatessen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSupSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/resources/logo-hachki.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/resources/toscana-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalCashToPayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCashToPayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCashToPayFieldActionPerformed

    private void buttonManjarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManjarActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.MANJAR_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.MANJAR_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonManjarActionPerformed

    private void buttonCoca600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCoca600ActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.COCA600_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.COCA600_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonCoca600ActionPerformed

    private void createNewSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewSaleBtnActionPerformed
        // TODO add your handling code here:
        productSaleViewController = new ProductSaleViewController(); 
    }//GEN-LAST:event_createNewSaleBtnActionPerformed

    private void buttonCoca1LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCoca1LActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.COCA1L_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.COCA1L_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonCoca1LActionPerformed

    private void buttonCocaLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCocaLightActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.COCALIGHT_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.COCALIGHT_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonCocaLightActionPerformed

    private void buttonNesteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNesteaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.NESTEA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.NESTEA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonNesteaActionPerformed

    private void buttonAguaNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAguaNaturalActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.AGUA_NATURAL_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.AGUA_NATURAL_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonAguaNaturalActionPerformed

    private void buttonExquisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExquisitaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.EXQUISITA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.EXQUISITA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonExquisitaActionPerformed

    private void buttonIrresistibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIrresistibleActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.IRRESISTEBLE_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.IRRESISTEBLE_PRODUCT_NAME);        
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonIrresistibleActionPerformed

    private void buttonSupAtunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupAtunActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.SUPR_AUTUN_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.SUPR_AUTUN_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonSupAtunActionPerformed

    private void buttonDeseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeseoActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.DESEO_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.DESEO_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonDeseoActionPerformed

    private void buttonDeliciosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeliciosaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.DELICIOSA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.DELICIOSA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonDeliciosaActionPerformed

    private void buttonMarcoPoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMarcoPoloActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.MARCOPOLO_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.MARCOPOLO_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonMarcoPoloActionPerformed

    private void buttonMixtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMixtaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.MIXTA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.MIXTA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonMixtaActionPerformed

    private void buttonToscanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToscanaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.TOSCANA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.TOSCANA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonToscanaActionPerformed

    private void buttonVegetarianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVegetarianaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.VEGETARIANA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.VEGETARIANA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonVegetarianaActionPerformed

    private void buttonVeneciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVeneciaActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.VENECIA_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.VENECIA_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonVeneciaActionPerformed

    private void buttonSupSalmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupSalmonActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.SUPR_SALMON_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.SUPR_SALMON_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonSupSalmonActionPerformed

    private void buttonDelicatessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelicatessenActionPerformed
        // TODO add your handling code here:
        productSaleViewController.addProductToSale(ProductsNames.DELICATESSEN_PRODUCT_NAME);
        productSaleViewController.increaseSaleTotalAmount(ProductsNames.DELICATESSEN_PRODUCT_NAME);
        productSaleViewController.refreshDataSaleUIElements(saleProductsTable,totalCashToPayField);
    }//GEN-LAST:event_buttonDelicatessenActionPerformed

    private void cashSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashSaleBtnActionPerformed
        // TODO add your handling code here:
        productSaleViewController.showCashPaymentUI(); //Cash es usado como verbo en este caso significando Cobrar
    }//GEN-LAST:event_cashSaleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIProductsSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIProductsSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIProductsSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIProductsSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIProductsSale sale = new UIProductsSale();
                sale.setExtendedState(MAXIMIZED_BOTH);
                sale.setVisible(true);
            }
        });
    }
   
    
    private ProductSaleViewController productSaleViewController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAguaNatural;
    private javax.swing.JButton buttonCoca1L;
    private javax.swing.JButton buttonCoca600;
    private javax.swing.JButton buttonCocaLight;
    private javax.swing.JButton buttonDelicatessen;
    private javax.swing.JButton buttonDeliciosa;
    private javax.swing.JButton buttonDeseo;
    private javax.swing.JButton buttonExquisita;
    private javax.swing.JButton buttonIrresistible;
    private javax.swing.JButton buttonManjar;
    private javax.swing.JButton buttonMarcoPolo;
    private javax.swing.JButton buttonMixta;
    private javax.swing.JButton buttonNestea;
    private javax.swing.JButton buttonSupAtun;
    private javax.swing.JButton buttonSupSalmon;
    private javax.swing.JButton buttonToscana;
    private javax.swing.JButton buttonVegetariana;
    private javax.swing.JButton buttonVenecia;
    private javax.swing.JButton cashSaleBtn;
    private javax.swing.JButton createNewSaleBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable saleProductsTable;
    private javax.swing.JTextField totalCashToPayField;
    // End of variables declaration//GEN-END:variables
}
// Cambiar saleProductsTable