/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.toscana.view.sale;

/**
 *
 * @author SG_05
 */
public class UIUseCashCount extends javax.swing.JDialog {

    /**
     * Creates new form UIUseCashCount
     */
    public UIUseCashCount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldPesos = new javax.swing.JTextField();
        textFieldDolares = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldTarjetas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textFieldTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Corte de Caja");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Pesos:");

        textFieldPesos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldPesos.setText("0.0");
        textFieldPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPesosActionPerformed(evt);
            }
        });
        textFieldPesos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPesosFocusLost(evt);
            }
        });

        textFieldDolares.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldDolares.setText("0.0");
        textFieldDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDolaresActionPerformed(evt);
            }
        });
        textFieldDolares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDolaresFocusLost(evt);
            }
        });

        jLabel3.setText("Dolares:");

        jLabel4.setText("Tarjetas:");

        textFieldTarjetas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldTarjetas.setText("0.0");
        textFieldTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTarjetasActionPerformed(evt);
            }
        });
        textFieldTarjetas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldTarjetasFocusLost(evt);
            }
        });

        jButton1.setText("Aceptar");

        textFieldTotal.setEditable(false);
        textFieldTotal.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        textFieldTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldPesos, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(textFieldDolares)
                            .addComponent(textFieldTarjetas)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPesosActionPerformed

    private void textFieldTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTarjetasActionPerformed

    private void textFieldPesosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPesosFocusLost
        /*int total = Integer.parseInt(textFieldTotal.getText().toString());
        total= total+ Integer.parseInt(textFieldPesos.getText());
        textFieldTotal.setText(total+"");*/
    }//GEN-LAST:event_textFieldPesosFocusLost

    private void textFieldDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDolaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDolaresActionPerformed

    private void textFieldDolaresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDolaresFocusLost
        int totalPesos = Integer.parseInt(textFieldPesos.getText().toString());
        int totalDolares = Integer.parseInt(textFieldDolares.getText().toString());
        int totalTarjetas = Integer.parseInt(textFieldTarjetas.getText().toString());
        int total= totalPesos + totalDolares + totalTarjetas;
        textFieldTotal.setText(total+"");
    }//GEN-LAST:event_textFieldDolaresFocusLost

    private void textFieldTarjetasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldTarjetasFocusLost
       /* int total = Integer.parseInt(textFieldTotal.getText().toString());
        total= total+ Integer.parseInt(textFieldTarjetas.getText());
        textFieldTotal.setText(total+"");*/
    }//GEN-LAST:event_textFieldTarjetasFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIUseCashCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIUseCashCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIUseCashCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIUseCashCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIUseCashCount dialog = new UIUseCashCount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textFieldDolares;
    private javax.swing.JTextField textFieldPesos;
    private javax.swing.JTextField textFieldTarjetas;
    private javax.swing.JTextField textFieldTotal;
    // End of variables declaration//GEN-END:variables
}
