/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toscana.view.admin;

import com.toscana.controller.admin.AdminViewController;

/**
 *
 * @author Arandi
 */
public class UIAdmin extends javax.swing.JFrame {

    /**
     * Creates new form UIAdmin
     */
    public UIAdmin() {
        initComponents();
        adminViewController = new AdminViewController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbedPane = new javax.swing.JTabbedPane();
        panelReports = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelProducts = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        buttonAddProduct = new javax.swing.JButton();
        buttonUpdateProduct = new javax.swing.JButton();
        buttonDeleteProduct = new javax.swing.JButton();
        panelUsers = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        buttonShowAddUser = new javax.swing.JButton();
        buttonShowUpdateUser = new javax.swing.JButton();
        buttonDeleteUser = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        labelUserPassword = new javax.swing.JLabel();
        fieldUserPassword = new javax.swing.JTextField();
        labelUserNickname = new javax.swing.JLabel();
        fieldUserNickname = new javax.swing.JTextField();
        labelUserPrivelege = new javax.swing.JLabel();
        buttonAddUser = new javax.swing.JButton();
        buttonUpdateUserData = new javax.swing.JButton();
        labelUserData = new javax.swing.JLabel();
        checkAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPane.setToolTipText("");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        javax.swing.GroupLayout panelReportsLayout = new javax.swing.GroupLayout(panelReports);
        panelReports.setLayout(panelReportsLayout);
        panelReportsLayout.setHorizontalGroup(
            panelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelReportsLayout.setVerticalGroup(
            panelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(442, Short.MAX_VALUE))
        );

        TabbedPane.addTab("<html><b><h3>Reportes</h3></b></html>", panelReports);

        labelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitulo1.setText("Administración de Productos");
        labelTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableProducts);

        buttonAddProduct.setText("Agregar");

        buttonUpdateProduct.setText("Editar");
        buttonUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateProductActionPerformed(evt);
            }
        });

        buttonDeleteProduct.setText("Eliminar");

        javax.swing.GroupLayout panelProductsLayout = new javax.swing.GroupLayout(panelProducts);
        panelProducts.setLayout(panelProductsLayout);
        panelProductsLayout.setHorizontalGroup(
            panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductsLayout.createSequentialGroup()
                .addGroup(panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonUpdateProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAddProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonDeleteProduct)))
                    .addGroup(panelProductsLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(labelTitulo1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductsLayout.setVerticalGroup(
            panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductsLayout.createSequentialGroup()
                        .addComponent(buttonAddProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonUpdateProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteProduct))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        TabbedPane.addTab("<html><b><h3>Productos</h3></b></html>", panelProducts);

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableUsers);

        buttonShowAddUser.setText("Agregar");
        buttonShowAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowAddUserActionPerformed(evt);
            }
        });

        buttonShowUpdateUser.setText("Editar");
        buttonShowUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowUpdateUserActionPerformed(evt);
            }
        });

        buttonDeleteUser.setText("Eliminar");
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitulo.setText("Administración de Usuarios");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelUserName.setText("Nombre");

        labelUserPassword.setText("Contraseña");

        labelUserNickname.setText("NickName");

        fieldUserNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserNicknameActionPerformed(evt);
            }
        });

        labelUserPrivelege.setText("Priveligios");

        buttonAddUser.setText("Agregar Usuario");
        buttonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddUserActionPerformed(evt);
            }
        });

        buttonUpdateUserData.setText("Actualizar Datos");

        labelUserData.setText("Datos Usuarios");

        checkAdmin.setText("Administrador");

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(labelTitulo))
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsersLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelUserData))
                            .addGroup(panelUsersLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(buttonShowUpdateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonShowAddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(buttonDeleteUser)))))
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelUsersLayout.createSequentialGroup()
                                    .addComponent(labelUserNickname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fieldUserNickname))
                                .addGroup(panelUsersLayout.createSequentialGroup()
                                    .addComponent(labelUserName)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonAddUser))
                        .addGap(31, 31, 31)
                        .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsersLayout.createSequentialGroup()
                                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUserPassword)
                                    .addComponent(labelUserPrivelege))
                                .addGap(18, 18, 18)
                                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkAdmin)))
                            .addGroup(panelUsersLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(buttonUpdateUserData)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addComponent(buttonShowAddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonShowUpdateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteUser))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserName)
                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserPassword)
                    .addComponent(fieldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserNickname)
                    .addComponent(fieldUserNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserPrivelege)
                    .addComponent(checkAdmin))
                .addGap(21, 21, 21)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddUser)
                    .addComponent(buttonUpdateUserData))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TabbedPane.addTab("<html><b><h3>Usuarios</h3></b></html>", panelUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.getAccessibleContext().setAccessibleName("<html><b><h3>Reportes</h3></b></html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowUpdateUserActionPerformed
        // TODO add your handling code here:
        clearUserFields();
        showUserFields(true);
        buttonUpdateUserData.setEnabled(true);
        buttonAddUser.setEnabled(false);
        adminViewController.getUserController().showUsersData(tableUsers, tableUsers.getSelectedRow(), fieldUserName, fieldUserName, fieldUserPassword, fieldUserNickname);
    }//GEN-LAST:event_buttonShowUpdateUserActionPerformed

    private void buttonUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateProductActionPerformed

    private void fieldUserNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserNicknameActionPerformed

    private void buttonShowAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowAddUserActionPerformed
        // TODO add your handling code here:
        clearUserFields();
        showUserFields(true);
        buttonUpdateUserData.setEnabled(false);
        buttonAddUser.setEnabled(true);
    }//GEN-LAST:event_buttonShowAddUserActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed
        // TODO add your handling code here:
        showUserFields(false);
    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void buttonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddUserActionPerformed
        // TODO add your handling code here:
        adminViewController.getUserController().saveUser(fieldUserName, fieldUserPassword, fieldUserNickname);
    }//GEN-LAST:event_buttonAddUserActionPerformed

    private void clearUserFields(){
        fieldUserName.setText("");
        fieldUserPassword.setText("");
        fieldUserNickname.setText("");
        
    }
    private void showUserFields(boolean isShown){
        labelUserData.setVisible(isShown);
        labelUserName.setVisible(isShown);
        labelUserPassword.setVisible(isShown);
        labelUserNickname.setVisible(isShown);
        labelUserPrivelege.setVisible(isShown);
        
        fieldUserName.setVisible(isShown);
        fieldUserPassword.setVisible(isShown);
        fieldUserNickname.setVisible(isShown);
        
        
        buttonAddUser.setVisible(isShown);
        buttonUpdateUserData.setVisible(isShown);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIAdmin uiAdmin = new UIAdmin();
                uiAdmin.setVisible(true);
                uiAdmin.showUserFields(false);
                
            }
        });
    }
    
    //  Variables declaration
    
    private AdminViewController adminViewController;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton buttonAddProduct;
    private javax.swing.JButton buttonAddUser;
    private javax.swing.JButton buttonDeleteProduct;
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonShowAddUser;
    private javax.swing.JButton buttonShowUpdateUser;
    private javax.swing.JButton buttonUpdateProduct;
    private javax.swing.JButton buttonUpdateUserData;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JTextField fieldUserNickname;
    private javax.swing.JTextField fieldUserPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelUserData;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserNickname;
    private javax.swing.JLabel labelUserPassword;
    private javax.swing.JLabel labelUserPrivelege;
    private javax.swing.JPanel panelProducts;
    private javax.swing.JPanel panelReports;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
